name: aplicacion2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/add.svg
    - assets/icono.svg
    - assets/Usuario.svg
    - assets/Cerrar.svg
    - assets/Notificaciones.svg
    - assets/Pantera.svg
    - assets/Privacidad.svg
    - assets/Registro.svg
    - assets/Fotografia.svg
    - assets/Correo.svg
    - assets/Avatar.svg
    - assets/logo.svg
    - assets/es.json
    - assets/en.json

  fonts:
    - family: FontRoboto
      fonts:
        - asset: assets/Roboto.ttf
    - family: FontConsolas
      fonts:
        - asset: assets/Consolas.ttf
